### PR TITLE
Added support for generic messages

### PR DESCRIPTION
**Pull request by mokkabonna**
I have added support for defining messages for generated validator names.

This will only be used if the validator does have no exactly matching message.

You define them like this:
```js
Vue.use(vuelidateErrorExtractor, {
  template: templates.foundation6,
  messages: {
    required: '{attribute} is required'
  },
  genericMessages: [{
    regexp: /.+/,
    message: '{attribute} has an error'
  }]
})
```

I tried to add testcases, but seems they are not running properly anyway, so did some changes to make them run.

Would you be willing to add something like this? My inspiration is this issue in my plugin: https://github.com/mokkabonna/vue-vuelidate-jsonschema/issues/4

Then I could define my generic messages like this:

```js
Vue.use(vuelidateErrorExtractor, {
  template: templates.foundation6,
  messages: {
    required: '{attribute} is required'
  },
  genericMessages: [{
    regexp: /^schemaPattern(\d+)?$/,
    message: '{schema.title} does not match pattern {schema.pattern}'
  }]
})
```

The first message to match the related regexp would be used.

This would match against all of:
```js
export default {
  validations: {
    schemaPattern: pattern('...'),
    schemaPattern2: pattern('...'),
    schemaPattern3: pattern('...')
    ...etc
  }
}
```

These would be auto generated by my library.

What do you think? Instead of a regexp it could also be a function that gets passed various params like key, messages, vm and need to return true or false depending on if we sould use the message or not.

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
Tests might not work because I kind of deleted most of the old boilerplate, thinking of using Jest as a test suite. 
Your idea is to have like a wildcard support for messages?
Would this be proprietary to your plugin or a common use case?

**Comment by mokkabonna** [comment]
Would be useful in any scenario where the exact validation keys are not fully known beforehand. Probably not that common use case.

However what is common and could be quite handy is to use the genericMessages to define a catch all message for any not defined in the explicit message list. It is easy to forget to define a message for a rule and then it would be useful to have a catch all rule.

```js
genericMessages: [{
  regexp: /.+/,
  message: '{attribute} has an error'
}]
```

**Comment by mokkabonna** [comment]
But I understand if you might hesitate to implement it in order to keep your library clean.

In the long run I might need to bundle a error extractor on my own in the plugin, since I might need more advanced and specific functionality. Like the ability to define functions that return messages instead of only templates.

**Comment by dobromir-hristov** [comment]
Why would you want to return false values?

**Comment by mokkabonna** [comment]
Ah, wasn't supposed to end up in the same PR.

But your current reduce code does not template values if they are falsy. They fall back to empty string.

So if I have minValue -5, it will be templated with empty string instead of -5. So in the changes I did I now rather check that the property is defined. If defined, always return the value, even if falsy. If not defined, return empty string.

**Comment by mokkabonna** [comment]
I was a bit quick there, the expression `-5 || ''` does return -5, but it's still true for the expression `0 || ''`, that does return empty string. So a minimum validator with value 0 will display empty string.

**Pull request closed without merging**
