### PR TITLE
Allow to translate attributes too

### PR DESCRIPTION
**Pull request by afwn90cj93201nixr2e1re**
Allow to translate attributes too
Fix build rollup-plugin-vue

### CODE REVIEW

**Comment by afwn90cj93201nixr2e1re** [comment]
@dobromir-hristov temp solution, if you can refactor this.

**Comment by dobromir-hristov** [comment]
Attributes are translatable, what was the idea behind this? Why push dist code to the pr, which change do I review...

**Comment by afwn90cj93201nixr2e1re** [comment]
Show me, how you gonna translate attribute field({attribute}).
Just close all files from dist folder.

**Comment by afwn90cj93201nixr2e1re** [comment]
```
"attributes": {
    "auth": "Authorization",
    "login": "Login-abc",
    "password": "Password 123",
    "text": "Text"
  },
  "validation": {
    "required": "The {attribute} field is required",
    "minLength": "Field {attribute} must be at less {min} characters",
    "maxLength": "Field {attribute} must be less than {max} characters"
  },
```

```
Vue.use(VuelidateErrorExtractor, {
    templates,
    i18n:'validation',//json key from translation file
    i18nAttributes:'attributes',//key from file
    messages:i18n.messages,//i18n.messages pointer
});
```

**Comment by dobromir-hristov** [comment]
https://dobromir-hristov.github.io/vuelidate-error-extractor/attributes.html#translatable-attributes
Looking at the docs you have two ways. Either put all of your attributes is your translations, near the messages, or map of attribute to path of translation.

I would suggest the first. so you just define a `__default` key and thats it.

```js
Vue.use(VuelidateErrorExtractor, {
  i18n: 'validations',
  i18nAttributes: {
    __default: 'attributes'
  }
})
```

```js
// your translation file
export default {
  validations: {},
  attributes: {}
}
```

**Comment by afwn90cj93201nixr2e1re** [comment]
So, what about en.json, ru.json etc file style using?

**Comment by dobromir-hristov** [comment]
I just used a js file for reference. You can use a json file too. Just put validations and attributes in each :)On 25 May 2019 17:53, afwn90cj93201nixr2e1re <notifications@github.com> wrote:So, what about en.json, ru.json etc file style using?

**Comment by afwn90cj93201nixr2e1re** [comment]
Im gonna try.

**Comment by afwn90cj93201nixr2e1re** [comment]
Thank's, that's work.

**Pull request closed without merging**
